repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=1000"]
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: text-unicode-replacement-char
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-alfred,
            flake8-bugbear,
            flake8-builtins,
            flake8-comprehensions,
            flake8-docstrings,
            flake8-eradicate,
            flake8-print,
            flake8-pytest-style,
            flake8-todo,
            flake8-typing-imports,
            flake8-unused-arguments,
            pep8-naming,
            pydocstyle,
            Pygments,
        ]
        args: [--ignore, "N806, D404, D100, D103, E800", --docstring-convention, "google"]
-   repo: https://github.com/guilatrova/tryceratops
    rev: v1.0.1
    hooks:
    -   id: tryceratops
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        args: [--skip, "*.html,*ipynb,*.bib,paper/"]

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-gfm,
            mdformat-black,
        ]
        args: [--wrap, "88"]
        files: (README.md)
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-myst,
            mdformat-black,
        ]
        args: [--wrap, "88"]
        files: (docs/.)
        # Exclude files with admonitions.
        # exclude: |
        #     (?x)^(
        #         path/to/file.py
        #     )$
-   repo: meta
    hooks:
    -   id: check-useless-excludes
